version: '3.7'
services:

  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs,sns,dynamodb
      EXTRA_CORS_ALLOWED_ORIGINS: "*"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DYNAMO_ENDPOINT: localstack:4566

  sqs-admin:
    image:  pacovk/sqs-admin
    ports:
      - "3999:3999"
    environment:
      SQS_ENDPOINT_URL: "http://localstack:4566"
      AWS_REGION: "eu-central-1"
    depends_on:
      - localstack