name: Application tests
on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:19-bullseye
    services:
      localstack:
        image: localstack/localstack:1.2.0
        env:
          SERVICES: sqs,sns,dynamodb
          EXTRA_CORS_ALLOWED_ORIGINS: "*"
    env:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_ENDPOINT: http://localstack:4566
    steps:
      - uses: actions/checkout@v3
      - name: Jest
        working-directory: application
        run: |
          yarn install
          yarn test