name: Infrastructure tests
on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTIONS_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Jest
        run: |
          yarn install
          cd infrastructure
          yarn get
          yarn test