name: Infrastructure tests
on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Jest
        run: |
          yarn install
          cd infrastructure
          yarn get
          yarn test