name: Infrastructure tests
on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Jest
        run: |
          cd infrastructure
          yarn global add cdktf-cli
          yarn --cwd ../application install && yarn install
          yarn get
          yarn test